name: clp-backend
services:
- name: api
  source_dir: /backend
  github:
    repo: hpeixotosp/clp
    branch: master
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: PORT
    value: "8080"
  - key: ENVIRONMENT
    value: production
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_HOST
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_USER
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_PASSWORD
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: MYSQL_DATABASE
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: GOOGLE_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET